version: '3.8'
services:
  wordpress:
    container_name: wordpress_container
    image: wordpress:latest
    ports:
      - "8799:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database
    depends_on:
      - db
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      - wp_network

  db:
    container_name: mysql_container
    image: mysql:5.7
    ports:
      - "8788:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - ./db_data_1:/var/lib/mysql
      # - ./schema:/docker-entrypoint-initdb.d
    networks:
      - wp_network

volumes:
  wordpress_data:
  db_data_1:
networks:
  wp_network:
    driver: bridge
