version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8799:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database
    depends_on:
      - db
    volumes:
      - ./wordpress_data_1:/var/www/html

  db:
    image: mysql:5.7
    ports:
      - "8788:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - ./db_data_1:/var/lib/mysql
  #### Second Paralle site    
  wordpress:
    image: wordpress:latest
    ports:
      - "8796:80"
    environment:
      WORDPRESS_DB_HOST: db_2
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database
    depends_on:
      - db_2
    volumes:
      - ./wordpress_data_2:/var/www/html

  db_2:
    image: mysql:5.7
    ports:
      - "8787:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - ./db_data_2:/var/lib/mysql

volumes:
  wordpress_data_1:
  db_data_1:
  wordpress_data_2:
  db_data_2:
